[package]
name = "cargo_semver_check"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trustfall_core = "0.0.2"
rustdoc-types = "0.11.0"
clap = { version = "3.2.8", features = ["cargo"] }
serde_json = "1.0.82"
anyhow = "1.0.58"
ron = "0.7.1"
serde = { version = "1.0.139", features = ["derive"] }
